analytics: {}
color:
  brandColors:
    - '#000000'
    - '#807304'
    - '#000000'
    - '#E8D008'
    - '#000000'
  brandStrength: 0.284628
  lightness: 0.496245
  rhythmicContrast: 0.506257
  saturation: 0.493742
cta: {}
layout_spectrum: 0.4236546
name: 'NC&M'
opengraph: {}
purpose: {}
typography_spectrum: 0.817568
