analytics: {}
color:
  brandColors:
    - '#000000'
    - '#807304'
    - '#000000'
    - '#E8D008'
    - '#000000'
  brandStrength: 0.499202
  lightness: 0.617869
  rhythmicContrast: 0.08817
  saturation: 0.04996
cta: {}
layout_spectrum: 0.883446
name: 'NC&M'
opengraph: {}
purpose: {}
typography_spectrum: 0.817568
