analytics: {}
color:
  brandColors:
    - '#000000'
    - '#807304'
    - '#000000'
    - '#E8D008'
    - '#000000'
  brandStrength: 0.756757
  lightness: 0.382601
  rhythmicContrast: 0.3125
  saturation: 0.205236
cta: {}
layout_spectrum: 0.883446
name: 'NC&M'
opengraph: {}
purpose: {}
typography_spectrum: 0.817568
