analytics: {}
color:
  brandColors:
    - '#000000'
    - '#807304'
    - '#000000'
    - '#E8D008'
    - '#000000'
  brandStrength: 0.339527
  lightness: 1
  rhythmicContrast: 1
  saturation: 0.997466
cta: {}
layout_spectrum: 0.17652
name: 'NC&M'
opengraph: {}
purpose: {}
typography_spectrum: 0.817568
